/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:86ba7fef-c20b-4623-be1e-d4af13c0b2c0",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_mcvnvaRf6",
    "aws_user_pools_web_client_id": "3sv0qn969s99c9l7nic9clco54",
    "oauth": {
        "domain": "5jg4pabr8sr0-staging.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,http://localhost:3001/,https://5jg4pabr8sr0-staging.auth.us-east-2.amazoncognito.com/oauth2/idpresponse,https://rinku2.d26pbs75zpbvmr.amplifyapp.com/pages/updateProfile,https://rinku2.d26pbs75zpbvmr.amplifyapp.com/*",
        "redirectSignOut": "http://localhost:3000/,http://localhost:3001/,https://5jg4pabr8sr0-staging.auth.us-east-2.amazoncognito.com/oauth2/idpresponse,https://rinku2.d26pbs75zpbvmr.amplifyapp.com/pages/updateProfile,https://rinku2.d26pbs75zpbvmr.amplifyapp.com/*",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ]
};


export default awsmobile;
