/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: process.env.NEXT_PUBLIC_aws_project_region,
  aws_cognito_identity_pool_id: process.env.NEXT_PUBLIC_aws_cognito_identity_pool_id,
  aws_cognito_region: process.env.aws_cognito_region,
  aws_user_pools_id: process.env.NEXT_PUBLIC_aws_user_pools_id,
  aws_user_pools_web_client_id: process.env.NEXT_PUBLIC_aws_user_pools_web_client_id,
  oauth: {
    domain: process.env.NEXT_PUBLIC_domain,
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: process.env.NEXT_PUBLIC_redirectSignIn,
    redirectSignOut: process.env.redirectSignOut,
    responseType: "code",
  },
  federationTarget: "COGNITO_USER_POOLS",
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: ["GOOGLE"],
  aws_cognito_signup_attributes: ["EMAIL"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [
      "REQUIRES_LOWERCASE",
      "REQUIRES_NUMBERS",
      "REQUIRES_SYMBOLS",
      "REQUIRES_UPPERCASE",
    ],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
  Auth: {
    region: process.env.NEXT_PUBLIC_region,
    userPoolId: process.env.NEXT_PUBLIC_userPoolId,
    userPoolWebClientId: process.env.NEXT_PUBLIC_userPoolWebClientId,
    identityPoolId: process.env.NEXT_PUBLIC_identityPoolId,
  },
  API: {
    endpoints: [
      {
        name: "YOUR_API_NAME",
        endpoint: "YOUR_API_ENDPOINT",
      },
    ],
  },
};

export default awsmobile;
