/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": process.env.aws_project_region,
    "aws_cognito_identity_pool_id": process.env.aws_cognito_identity_pool_id,
    "aws_cognito_region": process.env.aws_cognito_region,
    "aws_user_pools_id": process.env.aws_user_pools_id,
    "aws_user_pools_web_client_id": process.env.aws_user_pools_web_client_id,
    "oauth": {
        "domain": process.env.domain,
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": process.env.redirectSignIn,
        "redirectSignOut": process.env.redirectSignOut,
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "Auth": {
        "region": process.env.region,
        "userPoolId": process.env.userPoolId,
        "userPoolWebClientId": process.env.userPoolWebClientId,
        "identityPoolId": process.env.identityPoolId
    },
    "API": {
        "endpoints": [
            {
                "name": "YOUR_API_NAME",
                "endpoint": "YOUR_API_ENDPOINT"
            }
        ]
    }
};


export default awsmobile;
